quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=fruits
quarkus.datasource.password=fruits
quarkus.datasource.jdbc.max-size=50
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fruits
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fruits

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.second-level-caching-enabled=true
quarkus.hibernate-orm.jdbc.statement-fetch-size=16
quarkus.hibernate-orm.fetch.batch-size=16

quarkus.jackson.serialization-inclusion=non-empty

quarkus.micrometer.export.prometheus.enabled=true
quarkus.otel.traces.sampler=traceidratio
quarkus.otel.traces.sampler.arg=0.1

%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.image-name=postgres:17
%test.quarkus.datasource.username=fruits
%test.quarkus.datasource.password=fruits
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=import.sql
%test.quarkus.otel.sdk.disabled=true
