INSERT INTO fruits (id, name, description) VALUES (1, 'Apple', 'Hearty fruit');
INSERT INTO fruits (id, name, description) VALUES (2, 'Pear', 'Soft green fruit');
INSERT INTO fruits (id, name, description) VALUES (3, 'Banana', 'Fruit with appeal');
INSERT INTO fruits (id, name, description) VALUES (4, 'Orange', 'Citrus fruit');
INSERT INTO fruits (id, name, description) VALUES (5, 'Strawberry', 'Sweet red fruit');
INSERT INTO fruits (id, name, description) VALUES (6, 'Mango', 'Tropical stone fruit');
INSERT INTO fruits (id, name, description) VALUES (7, 'Grape', 'Small vine fruit');
INSERT INTO fruits (id, name, description) VALUES (8, 'Pineapple', 'Spiky tropical fruit');
INSERT INTO fruits (id, name, description) VALUES (9, 'Watermelon', 'Large summer fruit');
INSERT INTO fruits (id, name, description) VALUES (10, 'Kiwi', 'Tart green fruit');

INSERT INTO stores (id, name, currency, address, city, country) VALUES (1, 'Store 1', 'USD', '123 Main St', 'Anytown', 'USA');
INSERT INTO stores (id, name, currency, address, city, country) VALUES (2, 'Store 2', 'EUR', '456 Market St', 'Madrid', 'Spain');
INSERT INTO stores (id, name, currency, address, city, country) VALUES (3, 'Store 3', 'GBP', '789 High St', 'London', 'UK');
INSERT INTO stores (id, name, currency, address, city, country) VALUES (4, 'Store 4', 'JPY', '1 Chuo Ave', 'Tokyo', 'Japan');
INSERT INTO stores (id, name, currency, address, city, country) VALUES (5, 'Store 5', 'CAD', '22 Maple Rd', 'Toronto', 'Canada');
INSERT INTO stores (id, name, currency, address, city, country) VALUES (6, 'Store 6', 'AUD', '77 Harbour St', 'Sydney', 'Australia');
INSERT INTO stores (id, name, currency, address, city, country) VALUES (7, 'Store 7', 'EUR', '12 Rue Centrale', 'Paris', 'France');
INSERT INTO stores (id, name, currency, address, city, country) VALUES (8, 'Store 8', 'MXN', '88 Reforma Ave', 'Mexico City', 'Mexico');

INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (1, 1, 1.29);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (1, 2, 1.49);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (1, 3, 0.79);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (1, 4, 0.99);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (1, 5, 2.99);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (2, 1, 1.19);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (2, 3, 0.69);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (2, 6, 2.49);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (2, 7, 1.99);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (3, 2, 1.39);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (3, 4, 0.89);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (3, 8, 3.99);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (3, 10, 0.59);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (4, 1, 160.00);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (4, 5, 420.00);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (4, 6, 350.00);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (4, 9, 980.00);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (5, 3, 0.89);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (5, 4, 1.09);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (5, 7, 2.19);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (5, 9, 5.99);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (6, 1, 1.89);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (6, 6, 3.49);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (6, 8, 4.99);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (6, 10, 0.99);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (7, 2, 1.29);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (7, 5, 3.29);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (7, 7, 2.09);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (7, 8, 4.49);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (8, 3, 14.90);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (8, 4, 18.50);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (8, 6, 39.90);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (8, 9, 75.00);
INSERT INTO store_fruit_prices (store_id, fruit_id, price) VALUES (8, 10, 12.50);

ALTER SEQUENCE fruits_seq RESTART WITH 11;
ALTER SEQUENCE stores_seq RESTART WITH 9;
