micronaut.application.name=micronaut-fruit-store

datasources.default.db-type=postgres
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.url=jdbc:postgresql://localhost:5432/fruits
datasources.default.username=fruits
datasources.default.password=fruits
datasources.default.maximum-pool-size=50

jpa.default.entity-scan.packages=org.acme.domain
jpa.default.properties.hibernate.hbm2ddl.auto=create-drop
jpa.default.properties.hibernate.hbm2ddl.import_files=import.sql
jpa.default.properties.hibernate.default_batch_fetch_size=16
jpa.default.properties.hibernate.cache.use_second_level_cache=false
jpa.default.properties.hibernate.show_sql=false
jpa.default.properties.hibernate.open-in-view=false

jackson.serialization-inclusion=NON_EMPTY

endpoints.health.enabled=true
endpoints.health.sensitive=false
endpoints.prometheus.enabled=true
endpoints.prometheus.sensitive=false
micronaut.metrics.enabled=true
micronaut.metrics.export.prometheus.enabled=true
micronaut.metrics.export.prometheus.descriptions=true
micronaut.metrics.export.prometheus.step=PT1M

otel.traces.exporter=otlp
otel.traces.sampler=traceidratio
otel.traces.sampler.arg=0.1
